name: huawei_iap
description: HUAWEI IAP Kit plugin for Flutter.  Huawei's In-App Purchases (IAP) service allows you to offer in-app purchases and facilitates in-app payment.
version: 5.0.2+301
homepage: https://www.huawei.com
repository: https://github.com/HMS-Core/hms-flutter-plugin/tree/master/flutter-hms-iap

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.6 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.huawei.hms.flutter.iap
        pluginClass: IapPlugin
