name: huawei_scan_example
description: Demonstrates how to use the scan_flutter plugin.
version: 1.3.0+300

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  huawei_scan:
    path: ../

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/aztecBarcode.png
    - assets/multipleBarcode.png
    - assets/multipleBarcode2.png
    - assets/scan_kit_logo.png
