name: huawei_fido
description: HUAWEI FIDO Kit plugin for Flutter. It provides your app with FIDO2 based on the WebAuthn standart.
version: 5.0.5+305
homepage: https://www.huawei.com
repository: https://github.com/HMS-Core/hms-flutter-plugin/tree/master/flutter-hms-fido

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.6 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.huawei.hms.flutter.fido
        pluginClass: HuaweiFidoPlugin