name: huawei_hmsavailability
description: HUAWEI Availability Plugin for Flutter. It allows you to detect whether HMS Core apk is installed on a device.
version: 5.2.0+300
homepage: https://www.huawei.com
repository: https://github.com/HMS-Core/hms-flutter-plugin/tree/master/flutter-hms-hmsavailability

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.6 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.huawei.hms.flutter.hmsavailability
        pluginClass: HuaweiAvailabilityPlugin
