name: huawei_account
description: HUAWEI Account Kit plugin for Flutter. It enables user login processes to be carried out quickly and easily with HUAWEI Account Kit's two factor authentication.
version: 5.2.0+300
homepage: https://www.huawei.com
repository: https://github.com/HMS-Core/hms-flutter-plugin/tree/master/flutter-hms-account

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.6 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.huawei.hms.flutter.account
        pluginClass: HmsAccountPlugin

  assets:
    - packages/huawei_account/src/ui/logo.png
    - packages/huawei_account/src/ui/logored.png
