name: huawei_location
description: HUAWEI Flutter Location Kit plugin combines the Global Navigation Satellite System (GNSS), Wi-Fi, and base station location functionalities into your app.
version: 5.1.0+301
homepage: https://www.huawei.com
repository: https://github.com/HMS-Core/hms-flutter-plugin/tree/master/flutter-hms-location

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.6 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.huawei.hms.flutter.location
        pluginClass: LocationPlugin
