name: huawei_drive_example
description: Demonstrates how to use the huawei_drive plugin.
version: 5.0.0+303

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  huawei_account: 5.0.3+303
  huawei_drive:
    path: ../
  path_provider: ^1.6.11

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets: 
    - assets/test.txt
    - assets/demoImage.jpg
