name: huawei_ar
description: Huawei AR Engine Flutter Plugin is a platform for building augmented reality (AR) apps on Android
  smartphones using the Flutter framework.
version: 2.13.0+5
homepage: https://www.huawei.com
repository: https://github.com/HMS-Core/hms-flutter-plugin/tree/master/flutter-hms-ar

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.6 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.huawei.hms.flutter.ar
        pluginClass: AREnginePlugin
