name: huawei_contactshield
description: To help confront the global pandemic of coronavirus disease 2019, Huawei provides Contact Shield for developers to develop epidemic prevention and control apps.
version: 5.1.0+301
homepage: https://www.huawei.com
repository: https://github.com/HMS-Core/hms-flutter-plugin/tree/master/flutter-hms-contact-shield

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.6 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.huawei.hms.flutter.contactshield
        pluginClass: ContactShieldPlugin
